export type Difficulty = 'kids' | 'everyone' | 'adults'
export type GameLevel = 'easy' | 'medium' | 'hard'

export const LEVEL_LABELS: Record<GameLevel, { label: string; stars: string; color: string }> = {
  easy: { label: 'Easy', stars: '⭐', color: '#10b981' },
  medium: { label: 'Medium', stars: '⭐⭐', color: '#f59e0b' },
  hard: { label: 'Hard', stars: '⭐⭐⭐', color: '#ef4444' },
}

export interface GameInfo {
  id: string
  name: string
  icon: string
  color: string
  difficulty: Difficulty
  description: string
  controls: string
}

export const GAMES: GameInfo[] = [
  // === KIDS (Easy) ===
  {
    id: 'snake',
    name: 'Snake',
    icon: '🐍',
    color: '#10b981',
    difficulty: 'kids',
    description: 'Eat food, grow longer!',
    controls: 'Swipe or arrow keys',
  },
  {
    id: 'whack-a-mole',
    name: 'Whack-a-Mole',
    icon: '🔨',
    color: '#f59e0b',
    difficulty: 'kids',
    description: 'Tap the moles before they hide!',
    controls: 'Tap to whack',
  },
  {
    id: 'memory-match',
    name: 'Memory Match',
    icon: '🃏',
    color: '#ec4899',
    difficulty: 'kids',
    description: 'Find all the matching pairs!',
    controls: 'Tap to flip cards',
  },
  {
    id: 'tic-tac-toe',
    name: 'Tic-Tac-Toe',
    icon: '❌',
    color: '#8b5cf6',
    difficulty: 'kids',
    description: 'Get three in a row!',
    controls: 'Tap to place',
  },
  {
    id: 'simon',
    name: 'Simon Says',
    icon: '🔴',
    color: '#ef4444',
    difficulty: 'kids',
    description: 'Remember the color pattern!',
    controls: 'Tap the colors',
  },
  {
    id: 'dino-run',
    name: 'Dino Run',
    icon: '🦖',
    color: '#6b7280',
    difficulty: 'kids',
    description: 'Jump over cacti!',
    controls: 'Tap or spacebar to jump',
  },
  {
    id: 'pong',
    name: 'Pong',
    icon: '🏓',
    color: '#06b6d4',
    difficulty: 'kids',
    description: 'Classic paddle ball!',
    controls: 'Drag or arrow keys',
  },
  {
    id: 'connect-four',
    name: 'Connect Four',
    icon: '🔴',
    color: '#dc2626',
    difficulty: 'kids',
    description: 'Drop four in a row!',
    controls: 'Tap column to drop',
  },
  {
    id: 'breakout',
    name: 'Breakout',
    icon: '🧱',
    color: '#f97316',
    difficulty: 'kids',
    description: 'Break all the bricks!',
    controls: 'Drag or arrow keys',
  },
  {
    id: 'flappy-bird',
    name: 'Flappy Bird',
    icon: '🐦',
    color: '#84cc16',
    difficulty: 'kids',
    description: 'Fly through the pipes!',
    controls: 'Tap to flap',
  },
  {
    id: 'hangman',
    name: 'Hangman',
    icon: '📝',
    color: '#a855f7',
    difficulty: 'kids',
    description: 'Guess the word!',
    controls: 'Tap letters',
  },
  {
    id: '2048',
    name: '2048',
    icon: '🔢',
    color: '#eab308',
    difficulty: 'kids',
    description: 'Merge tiles to reach 2048!',
    controls: 'Swipe or arrow keys',
  },
  // === ADULTS (Harder) ===
  {
    id: 'tetris',
    name: 'Tetris',
    icon: '🟦',
    color: '#3b82f6',
    difficulty: 'adults',
    description: 'Stack and clear lines!',
    controls: 'Swipe or arrow keys',
  },
  {
    id: 'space-invaders',
    name: 'Space Invaders',
    icon: '👾',
    color: '#22c55e',
    difficulty: 'adults',
    description: 'Defend Earth from aliens!',
    controls: 'Drag to move, tap to shoot',
  },
  {
    id: 'pac-man',
    name: 'Pac-Man',
    icon: '🟡',
    color: '#facc15',
    difficulty: 'adults',
    description: 'Eat dots, avoid ghosts!',
    controls: 'Swipe or arrow keys',
  },
  {
    id: 'asteroids',
    name: 'Asteroids',
    icon: '☄️',
    color: '#a1a1aa',
    difficulty: 'adults',
    description: 'Blast space rocks!',
    controls: 'Arrow keys + space to shoot',
  },
  {
    id: 'frogger',
    name: 'Frogger',
    icon: '🐸',
    color: '#4ade80',
    difficulty: 'adults',
    description: 'Cross the road safely!',
    controls: 'Swipe or arrow keys',
  },
  {
    id: 'minesweeper',
    name: 'Minesweeper',
    icon: '💣',
    color: '#64748b',
    difficulty: 'adults',
    description: 'Clear the minefield!',
    controls: 'Tap to reveal, long-press to flag',
  },
  {
    id: 'wordle',
    name: 'Wordle',
    icon: '🟩',
    color: '#16a34a',
    difficulty: 'adults',
    description: 'Guess the 5-letter word!',
    controls: 'Type letters',
  },
  {
    id: 'galaga',
    name: 'Galaga',
    icon: '🚀',
    color: '#e11d48',
    difficulty: 'adults',
    description: 'Shoot alien formations!',
    controls: 'Drag to move, tap to shoot',
  },
  {
    id: 'checkers',
    name: 'Checkers',
    icon: '⚫',
    color: '#b45309',
    difficulty: 'adults',
    description: 'Jump and capture!',
    controls: 'Tap piece, then tap destination',
  },
  {
    id: 'brick-breaker',
    name: 'Brick Breaker',
    icon: '💥',
    color: '#7c3aed',
    difficulty: 'adults',
    description: 'Smash bricks with power-ups!',
    controls: 'Drag or arrow keys',
  },
  {
    id: 'crossy-road',
    name: 'Crossy Road',
    icon: '🐔',
    color: '#65a30d',
    difficulty: 'adults',
    description: 'Cross roads and rivers!',
    controls: 'Swipe to move',
  },
  {
    id: 'doodle-jump',
    name: 'Doodle Jump',
    icon: '⬆️',
    color: '#0ea5e9',
    difficulty: 'adults',
    description: 'Bounce higher and higher!',
    controls: 'Tilt or arrow keys',
  },
  {
    id: 'chess',
    name: 'Chess',
    icon: '♟️',
    color: '#c084fc',
    difficulty: 'adults',
    description: 'Classic strategy game!',
    controls: 'Tap piece, then tap destination',
  },
  {
    id: 'rummy-500',
    name: 'Rummy 500',
    icon: '🃑',
    color: '#06b6d4',
    difficulty: 'adults',
    description: 'Meld sets and runs to 500!',
    controls: 'Tap to select, meld, or discard',
  },
  {
    id: 'crazy-eights',
    name: 'Crazy Eights',
    icon: '8️⃣',
    color: '#a78bfa',
    difficulty: 'everyone',
    description: 'Play 8s wild and empty your hand!',
    controls: 'Tap card to play, tap deck to draw',
  },
  {
    id: 'go-fish',
    name: 'Go Fish',
    icon: '🐟',
    color: '#06b6d4',
    difficulty: 'everyone',
    description: 'Collect books of four!',
    controls: 'Tap card, then tap a player to ask',
  },
  {
    id: 'hearts',
    name: 'Hearts',
    icon: '♥️',
    color: '#ef4444',
    difficulty: 'everyone',
    description: 'Avoid hearts and the Queen of Spades!',
    controls: 'Tap card to play',
  },
  {
    id: 'spades',
    name: 'Spades',
    icon: '♠️',
    color: '#e2e8f0',
    difficulty: 'everyone',
    description: 'Bid and win tricks with your partner!',
    controls: 'Tap card to play',
  },
  {
    id: 'war',
    name: 'War',
    icon: '⚔️',
    color: '#ef4444',
    difficulty: 'everyone',
    description: 'Flip cards — higher wins!',
    controls: 'Tap to flip cards',
  },
  {
    id: 'blackjack',
    name: 'Blackjack',
    icon: '🃏',
    color: '#10b981',
    difficulty: 'everyone',
    description: 'Beat the dealer to 21!',
    controls: 'Tap Hit, Stand, or Double',
  },
  {
    id: 'solitaire',
    name: 'Solitaire',
    icon: '🂡',
    color: '#16a34a',
    difficulty: 'everyone',
    description: 'Classic Klondike — build Ace to King!',
    controls: 'Tap to select and move cards',
  },
  {
    id: 'old-maid',
    name: 'Old Maid',
    icon: '👵',
    color: '#ec4899',
    difficulty: 'kids',
    description: 'Don\'t get stuck with the Queen!',
    controls: 'Tap a card to draw from opponent',
  },
  {
    id: 'poker',
    name: 'Texas Hold\'em',
    icon: '🃏',
    color: '#f59e0b',
    difficulty: 'adults',
    description: 'Bluff, bet, and beat the table!',
    controls: 'Tap actions: fold, check, call, raise',
  },
  {
    id: 'color-clash',
    name: 'Color Clash',
    icon: '🌈',
    color: '#8b5cf6',
    difficulty: 'everyone',
    description: 'UNO-style — match colors or values!',
    controls: 'Tap card to play, tap deck to draw',
  },
  {
    id: 'gin-rummy',
    name: 'Gin Rummy',
    icon: '🂠',
    color: '#d97706',
    difficulty: 'everyone',
    description: 'Meld sets and runs, knock to win!',
    controls: 'Tap to draw, tap card to discard',
  },
  {
    id: 'euchre',
    name: 'Euchre',
    icon: '🂫',
    color: '#7c3aed',
    difficulty: 'everyone',
    description: 'Trick-taking with a trump suit!',
    controls: 'Tap card to play',
  },
  {
    id: 'cribbage',
    name: 'Cribbage',
    icon: '🔢',
    color: '#b45309',
    difficulty: 'adults',
    description: 'Peg your way to 121!',
    controls: 'Tap cards to select, tap to discard to crib',
  },
  {
    id: 'snap',
    name: 'Snap',
    icon: '👋',
    color: '#f59e0b',
    difficulty: 'kids',
    description: 'Slap first when two cards match!',
    controls: 'Tap Flip, tap SLAP on a match',
  },
]

export function getGameById(id: string): GameInfo | undefined {
  return GAMES.find(g => g.id === id)
}

export function getGamesByDifficulty(diff: Difficulty): GameInfo[] {
  return GAMES.filter(g => g.difficulty === diff)
}
